-- AlterTable
ALTER TABLE "Lawyer" ALTER COLUMN "cpf" DROP NOT NULL,
ALTER COLUMN "specialization" DROP NOT NULL,
ALTER COLUMN "oab_number" DROP NOT NULL,
ALTER COLUMN "phone" DROP NOT NULL,
ALTER COLUMN "password" DROP NOT NULL,
ALTER COLUMN "oab_state" DROP NOT NULL;
